- name: Install apache
  ansible.builtin.apt:
    name: apache2
    state: present #install
    update_cache: yes #sudo apt update

- name: Start service apache
  ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes