- name: Download wordpress
  ansible.builtin.get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress.tar.gz #download the latest version of wordpress without providing version

- name: Extract wordpress
  ansible.builtin.unarchive:
    src: /tmp/wordpress.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /tmp/wordpress/. # we can't use '*' in ansible, instead '.' 
    dest: /var/www/html
    owner: www-data #owner/group names for Ubuntu machines
    group: www-data
    mode: '0755'   
    remote_src: yes

- name: Remove file (delete file)
  ansible.builtin.file:
    path: /var/www/html/index.html
    state: absent #delete
