- name: Install apache
  ansible.builtin.dnf:
    name: httpd
    state: present 

- name: Start service httpd and enable
  ansible.builtin.service:
      name: httpd
      state: started
      enabled: yes