- name: Install apache
  ansible.builtin.apt:
    name: apache2
    state: present #install
    update_cache: yes

- name: Start service apache and enable
  ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes