- name: Install mysql
  ansible.builtin.apt:
    name: mysql-server
    state: present 
    update_cache: yes #sudo apt update

- name: Start service mysql
  ansible.builtin.service:
      name: mysql
      state: started
      enabled: yes

- name: Install PyMySQL
  ansible.builtin.apt:
    name: python3-pymysql
    state: present       

- name: Create a new database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present #create
    login_unix_socket: /run/mysqld/mysqld.sock #ansible will use this file to access mysql

- name: Create database user
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_pass }}"
    priv: '*.*:ALL'
    state: present
    login_unix_socket: /run/mysqld/mysqld.sock
